# This is a basic workflow to help you get started with Actions

name: Compress Json Schemas

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2.3.4

      - uses: DaanV2/Json-Schema-Action-Compression@v1.1
        with:
          specificationFile: "${{github.workspace}}\\source\\compress_specification.json"
      
      - name: Commit changes
        continue-on-error: true
        run: |
          cd ${{github.workspace}}
          git config --global user.email "Bot@Blockception.com"
          git config --global user.name "Blockception Bot"
          git add .
          git commit -m "auto: Generated Json Schemas"
          git push
